export enum ItemCategory {
  AMENITY = 'AMENITY',
  F_AND_B = 'F_AND_B',
  HOUSEKEEPING = 'HOUSEKEEPING',
  MAINTENANCE = 'MAINTENANCE',
  LINEN = 'LINEN',
  OTHER = 'OTHER',
}

export enum ItemUnit {
  PIECE = 'piece',
  BOTTLE = 'bottle',
  KG = 'kg',
  LITER = 'liter',
  PACK = 'pack',
  ROLL = 'roll',
  SET = 'set',
}

export enum StockIssueType {
  ROOM_AMENITY = 'ROOM_AMENITY',
  MINIBAR_CONSUMPTION = 'MINIBAR_CONSUMPTION',
  HOUSEKEEPING = 'HOUSEKEEPING',
  MAINTENANCE = 'MAINTENANCE',
  F_AND_B = 'F_AND_B',
  SUPPLY_KIT = 'SUPPLY_KIT',
  MINIBAR_RESTOCK = 'MINIBAR_RESTOCK',
  INTER_HOTEL_TRANSFER = 'INTER_HOTEL_TRANSFER',
  OTHER = 'OTHER',
}

export enum WarehouseScope {
  HOTEL = 'HOTEL',
  CHAIN = 'CHAIN',
}

export enum InterHotelTransferStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  IN_TRANSIT = 'IN_TRANSIT',
  RECEIVED = 'RECEIVED',
  REJECTED = 'REJECTED',
}

export enum TransferType {
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  INTER_COMPANY_SALE = 'INTER_COMPANY_SALE',
}

export enum StockAdjustmentType {
  STOCK_TAKE = 'STOCK_TAKE',
  DAMAGE = 'DAMAGE',
  EXPIRED = 'EXPIRED',
  WRITE_OFF = 'WRITE_OFF',
  RETURN_TO_STOCK = 'RETURN_TO_STOCK',
  RETURN_TO_SUPPLIER = 'RETURN_TO_SUPPLIER',
}
