/**
 * Room Status Enum
 */

export enum RoomStatus {
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  MAINTENANCE = 'MAINTENANCE',
  BLOCKED = 'BLOCKED',
  DIRTY = 'DIRTY',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
  OUT_OF_ORDER = 'OUT_OF_ORDER',
  CLEANING = 'CLEANING',
  CLEANING_REQUIRED = 'CLEANING_REQUIRED',
  INSPECTION = 'INSPECTION',
  CHECKOUT_PENDING = 'CHECKOUT_PENDING',
  INACTIVE = 'INACTIVE',
}

/**
 * Room Type Amenity Enum
 */

export enum RoomTypeAmenity {
  WIFI = 'WIFI',
  TV = 'TV',
  AC = 'AC',
  MINIBAR = 'MINIBAR',
  SAFE = 'SAFE',
  BATHTUB = 'BATHTUB',
  SHOWER = 'SHOWER',
  BALCONY = 'BALCONY',
  KITCHEN = 'KITCHEN',
  WASHER = 'WASHER',
  HAIRDRYER = 'HAIRDRYER',
  IRON = 'IRON',
  WORKSPACE = 'WORKSPACE',
}
