import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsOptional, IsUUID, IsNumber, IsEnum } from 'class-validator';
import { Type } from 'class-transformer';
import type { NatsResponse } from '../../common/nats-response.interface';

export enum ReferCodeType {
  CORPORATE = 'CORPORATE',
  TRAVEL_AGENT = 'TRAVEL_AGENT',
  STAFF = 'STAFF',
  AFFILIATE = 'AFFILIATE',
}

// --- Lookup ---

export class LookupReferCodeRequest {
  @ApiPropertyOptional() @IsOptional() @IsUUID() tenantId?: string;
  @ApiProperty({ description: 'Code to lookup' }) @IsString() code: string;
}

export class LookupReferCodeResponse {
  @ApiProperty() code: string;
  @ApiProperty({ enum: ReferCodeType }) referenceType: string;
  @ApiProperty() referenceId: string;
  @ApiProperty() displayName: string;
  @ApiProperty() isActive: boolean;
}

// --- CRUD ---

export class CreateReferCodeRequest {
  @ApiPropertyOptional() @IsOptional() @IsUUID() tenantId?: string;
  @ApiProperty({ description: 'Unique code (e.g., VINAMILK, SP-012)' }) @IsString() code: string;
  @ApiProperty({ description: 'Entity type', enum: ReferCodeType }) @IsEnum(ReferCodeType) referenceType: ReferCodeType;
  @ApiProperty({ description: 'Entity UUID' }) @IsUUID() referenceId: string;
  @ApiProperty({ description: 'Display name for quick reference' }) @IsString() displayName: string;
}

export class FindReferCodesRequest {
  @ApiPropertyOptional() @IsOptional() @IsUUID() tenantId?: string;
  @ApiPropertyOptional({ enum: ReferCodeType }) @IsOptional() @IsEnum(ReferCodeType) referenceType?: ReferCodeType;
  @ApiPropertyOptional() @IsOptional() @IsUUID() referenceId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() search?: string;
  @ApiPropertyOptional({ default: 1 }) @IsOptional() @IsNumber() @Type(() => Number) page?: number;
  @ApiPropertyOptional({ default: 50 }) @IsOptional() @IsNumber() @Type(() => Number) limit?: number;
}

export class DeleteReferCodeRequest {
  @ApiPropertyOptional() @IsOptional() @IsUUID() tenantId?: string;
  @ApiProperty() @IsUUID() id: string;
}

// --- Responses ---

export class ReferCodeResponse {
  @ApiProperty() id: string;
  @ApiProperty() tenantId: string;
  @ApiProperty() code: string;
  @ApiProperty({ enum: ReferCodeType }) referenceType: string;
  @ApiProperty() referenceId: string;
  @ApiProperty() displayName: string;
  @ApiProperty() isActive: boolean;
  @ApiProperty() isAutoGenerated: boolean;
  @ApiProperty() createdAt: Date;
}

export class ReferCodeListResponse {
  @ApiProperty({ type: [ReferCodeResponse] }) referCodes: ReferCodeResponse[];
  @ApiProperty() total: number;
  @ApiProperty() page: number;
  @ApiProperty() limit: number;
  @ApiProperty() totalPages: number;
}

export class DeleteReferCodeResponse {
  @ApiProperty() deleted: boolean;
}

// --- Typed NATS responses ---

export type LookupReferCodeNatsResponse = NatsResponse<LookupReferCodeResponse>;
export type CreateReferCodeNatsResponse = NatsResponse<ReferCodeResponse>;
export type FindReferCodesNatsResponse = NatsResponse<ReferCodeListResponse>;
export type DeleteReferCodeNatsResponse = NatsResponse<DeleteReferCodeResponse>;
