export enum BookingSource {
  DIRECT = 'DIRECT',
  WEBSITE = 'WEBSITE',
  PHONE = 'PHONE',
  EMAIL = 'EMAIL',
  WALK_IN = 'WALK_IN',
  TRAVEL_AGENT = 'TRAVEL_AGENT',
  CORPORATE = 'CORPORATE',
  OTA = 'OTA',
}
