/**
 * User Role Enum
 * Represents user roles in the SaziHotel system
 * Based on ROLES.md specification
 */

export enum UserRole {
  // === PLATFORM LEVEL ROLES ===
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  PLATFORM_OPERATIONS = 'PLATFORM_OPERATIONS',
  PLATFORM_BILLING = 'PLATFORM_BILLING',
  PLATFORM_ANALYTICS = 'PLATFORM_ANALYTICS',
  PLATFORM_SUPPORT = 'PLATFORM_SUPPORT',

  // === TENANT/CHAIN LEVEL ROLES ===
  CHAIN_OWNER = 'CHAIN_OWNER',
  CHAIN_MANAGER = 'CHAIN_MANAGER',

  // === HOTEL LEVEL ROLES ===
  HOTEL_MANAGER = 'HOTEL_MANAGER',
  ASSISTANT_MANAGER = 'ASSISTANT_MANAGER',

  // === FRONT OFFICE ROLES ===
  FRONT_DESK_MANAGER = 'FRONT_DESK_MANAGER',
  FRONT_DESK = 'FRONT_DESK',
  NIGHT_AUDITOR = 'NIGHT_AUDITOR',

  // === GUEST SERVICES ROLES ===
  GUEST_SERVICES_MANAGER = 'GUEST_SERVICES_MANAGER',
  CONCIERGE = 'CONCIERGE',

  // === HOUSEKEEPING ROLES ===
  HOUSEKEEPING_MANAGER = 'HOUSEKEEPING_MANAGER',
  HOUSEKEEPING_SUPERVISOR = 'HOUSEKEEPING_SUPERVISOR',
  HOUSEKEEPING_STAFF = 'HOUSEKEEPING_STAFF',

  // === FINANCIAL ROLES ===
  FINANCIAL_MANAGER = 'FINANCIAL_MANAGER',
  ACCOUNTING = 'ACCOUNTING',
  REVENUE_MANAGER = 'REVENUE_MANAGER',

  // === SALES & MARKETING ROLES ===
  SALES_MANAGER = 'SALES_MANAGER',
  MARKETING_MANAGER = 'MARKETING_MANAGER',

  // === CRM & CUSTOMER RELATIONS ===
  CRM_MANAGER = 'CRM_MANAGER',
  CRM_SPECIALIST = 'CRM_SPECIALIST',

  // === SERVICE & MAINTENANCE ROLES ===
  SERVICE_MANAGER = 'SERVICE_MANAGER',
  SERVICE_STAFF = 'SERVICE_STAFF',
  MAINTENANCE_MANAGER = 'MAINTENANCE_MANAGER',
  MAINTENANCE_STAFF = 'MAINTENANCE_STAFF',

  // === SECURITY ROLES ===
  SECURITY_MANAGER = 'SECURITY_MANAGER',
  SECURITY_STAFF = 'SECURITY_STAFF',

  // === SPECIAL ROLES ===
  GUEST = 'GUEST',
  VENDOR = 'VENDOR',

  // === LEGACY ROLES (for backward compatibility) ===
  NIGHT_SHIFT = 'NIGHT_SHIFT', // Alias for NIGHT_AUDITOR
}
